# Generated by Django 4.2.4 on 2023-08-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admindatabase',
            old_name='Emain',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='userdatabase',
            old_name='Emain',
            new_name='Email',
        ),
    ]
