# Generated by Django 4.2.4 on 2023-08-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_emain_admindatabase_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='queryDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Contact', models.IntegerField()),
                ('Query', models.CharField(max_length=300)),
            ],
        ),
    ]
